apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  labels:
    app: alertmanager
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9093
      nodePort: 30093
  selector:
    app: alertmanager
