apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30300
  selector:
    app: grafana
