apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels:
    app: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30090
  selector:
    app: prometheus
